import * as fs from 'fs/promises';
import * as path from 'path';
import { MigrationError, MigrationSeverity, migrationRules } from './rules';

export interface MigrationFinding {
	file: string;
	line: number;
	column: number;
	ruleId: string;
	severity: MigrationSeverity;
	snippet: string;
}

export interface MigrationScanResult {
	findings: MigrationFinding[];
	scanned: number;
	// C# files encountered but excluded. Files inside excluded directories are not enumerated.
	skipped: number;
	durationMs: number;
	ruleSetVersion: string;
	scannedAt: string;
}

const excludedDirectories = new Set(['library', 'temp', 'obj', 'bin', 'build', 'builds', 'logs', 'node_modules', '.git', '.vs']);

export async function scan(projectRoot: string): Promise<MigrationScanResult> {
	const started = Date.now();
	if (typeof projectRoot !== 'string' || projectRoot.trim().length === 0) {
		throw new MigrationError('PROJECT_UNREADABLE', 'The Unity project path is missing. The scan cannot start. Provide the project root.');
	}
	const root = path.resolve(projectRoot);
	const result: MigrationScanResult = {
		findings: [], scanned: 0, skipped: 0, durationMs: 0, ruleSetVersion: migrationRules.version, scannedAt: new Date(started).toISOString()
	};
	const patterns = migrationRules.rules.map(rule => ({ rule, regex: new RegExp(rule.pattern, 'gm') }));

	async function visit(directory: string): Promise<void> {
		const entries = await fs.readdir(directory, { withFileTypes: true });
		entries.sort((left, right) => left.name.localeCompare(right.name));
		for (const entry of entries) {
			const filePath = path.join(directory, entry.name);
			if (entry.isDirectory()) {
				if (!excludedDirectories.has(entry.name.toLowerCase())) {
					await visit(filePath);
				}
				continue;
			}
			if (!/\.cs$/i.test(entry.name)) {
				continue;
			}
			if (!entry.isFile() || /(?:\.g|\.generated|\.designer)\.cs$/i.test(entry.name)) {
				result.skipped++;
				continue;
			}
			const source = await fs.readFile(filePath, 'utf8');
			if (/^\s*(?:\/\/|\/\*|\*)\s*<auto-generated\b/im.test(source.slice(0, 2048))) {
				result.skipped++;
				continue;
			}
			result.scanned++;
			// Preserve offsets and newlines while hiding comments and string/character literals.
			const code = source.replace(/\/\/[^\r\n]*|\/\*[\s\S]*?\*\/|@"(?:[^"]|"")*"|"(?:\\[\s\S]|[^"\\])*"|'(?:\\.|[^'\\])*'/g,
				match => match.replace(/[^\r\n]/g, ' '));
			const lines = source.split(/\r?\n/);
			for (const { rule, regex } of patterns) {
				regex.lastIndex = 0;
				let match: RegExpExecArray | null;
				while ((match = regex.exec(code)) != null) {
					if (match[0].length === 0) {
						throw new MigrationError('RULES_INVALID', `Migration rule ${rule.id} matches empty text. The scan cannot finish. Correct the rule pattern.`);
					}
					const before = source.slice(0, match.index);
					const line = before.split('\n').length;
					result.findings.push({
						file: path.relative(root, filePath).split(path.sep).join('/'),
						line, column: match.index - before.lastIndexOf('\n'),
						ruleId: rule.id, severity: rule.severity, snippet: lines[line - 1].trim()
					});
				}
			}
		}
	}

	try {
		const entries = await fs.readdir(root, { withFileTypes: true });
		const roots = entries.filter(entry => entry.name === 'Assets' || entry.name === 'Packages');
		if (roots.length === 0 || roots.some(entry => !entry.isDirectory())) {
			throw new Error('Project scan directories are missing or invalid');
		}
		for (const name of ['Assets', 'Packages']) {
			if (roots.some(entry => entry.name === name)) {
				await visit(path.join(root, name));
			}
		}
	} catch (error) {
		if (error instanceof MigrationError) {
			throw error;
		}
		throw new MigrationError('PROJECT_UNREADABLE', `Unity project files cannot be read at ${root}. The scan cannot finish. Check the project path and read permissions.`);
	}

	result.findings.sort((left, right) => left.file.localeCompare(right.file)
		|| left.line - right.line || left.column - right.column || left.ruleId.localeCompare(right.ruleId));
	result.durationMs = Date.now() - started;
	return result;
}
